name: Notify Eva (Telegram)

on:
  workflow_run:
    workflows: [CI, Smoke]
    types: [completed]

jobs:
  notify:
    if: ${{ secrets.TELEGRAM_TOKEN != '' && secrets.TELEGRAM_CHAT_ID != '' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Send Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PR_URL: ${{ github.event.workflow_run.html_url }}
          REPO: ${{ github.repository }}
          STATUS: ${{ github.event.workflow_run.conclusion }}
        run: |
          curl -s --fail "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="HTML" \
            -d text="🧪 <b>${REPO}</b> • ${STATUS}\n${PR_URL}" || true
